### PR TITLE
tm-new-tiddler - Create empty tags field only if template or additionalFields contain a tags-field

### LINKED ISSUE #8553: [Bug] tm-new-tiddler message creates tags field even if it is empty. -- It should not
`tm-new-tiddler` message does create an empty `tags:` field, if there is no value set to: `$:/config/NewTiddler/Tags`

**To reproduce**

- Click the NewTiddler button at tw-com
- Save the new tiddler
- Open Tiddler (i)nfo area -> Fields tab

image

**Expected behaviour:** If there is no tag defined, there should be no tags-field

It is not a "doomsday" problem, but it is problem with Testcase Tiddlers, that contain buttons, that create a new tiddler using that message. Eg: **(simplified testcase)**

- Use the following code with a testcase-tiddler with https://tiddlywiki.com/prerelease/
- title: test-new-tiddler-button
- tag: $:/tags/wiki-test-spec
- type: text/vnd.tiddlywiki-multiple

```
title: Narrative

This code tests action-sendmessage with tm-new-tiddler

+
title: Output

<$button>
<$action-sendmessage $message="tm-new-tiddler" />
Create a new tiddler
</$button>
```

**Problem**: I did not specify an additional parameter, but the `tags` field is still there. That was very confusing with my real testcase, where I did create the docs for rewritten toc-macros. 

The `tags` field was there, but the code should have only created `tagLike` -- **So I started to investigate** 
Just to find out the that's the default behaviour for TW tm-new-tiddler message. -- time wasted.

image

**Proposal**

I would like to remove that redundant field, if it is empty. I think the change should be backwards compatible and it will save other developers some time once they start using the Testcase compound tiddlers.

### PR DESCRIPTION
**Pull request by pmario**
This PR fixes #8553

With this PR the tm-new-tiddler message only creates an empty tags field if template tiddler or additionalFields already contain a tags-field

- This makes it possible to define if an empty tag field should be created or not. 
- Default is **no** tags field, if there is no parameter - (that's different to the current behaviour, that causes an issue see: #8553)
- If the `action-sendmessage` has a paramter `tags=""` it will be created in the new tiddler
- If the parameter `$params=template` is use and the template tiddler contains a tags-field -- It will be copied over, even if it is empty

Code to test: 

```
<$button>
<$action-sendmessage $message="tm-new-tiddler" title="template" text=<<now "Today is DDth, MMM YYYY">> hugo="" />
New Tiddler 
</$button>

<$button>
<$action-sendmessage $message="tm-new-tiddler" title="template-tags" text=<<now "Today is DDth, MMM YYYY">> tags="" />
New Tiddler with tags=""
</$button>


<$button>
<$action-sendmessage $message="tm-new-tiddler" $param=template title="This is newly created tiddler" text=<<now "Today is DDth, MMM YYYY">> />
New Tiddler from template
</$button>

<$button>
<$action-sendmessage $message="tm-new-tiddler" $param=template title="This is newly created tiddler" text=<<now "Today is DDth, MMM YYYY">> tags="" />
New Tiddler from template, param tags=""
</$button>


<$button>
<$action-sendmessage $message="tm-new-tiddler" $param=template-tags title="This is newly created tiddler" text=<<now "Today is DDth, MMM YYYY">> />
New Tiddler from template-tags
</$button>
```

### CODE REVIEW

File: core/modules/widgets/navigator.js [hunk 1]
```diff
@@ -412,7 +412,7 @@ NavigatorWidget.prototype.handleNewTiddlerEvent = function(event) {
 	event = $tw.hooks.invokeHook("th-new-tiddler", event);
 	// Get the story details
 	var storyList = this.getStoryList(),
-		templateTiddler, additionalFields, title, draftTitle, existingTiddler;
+		templateTiddler, additionalFields, title, draftTitle, existingTiddler, templateHasTags=false;
```
Comment (Jermolene) [inline core/modules/widgets/navigator.js:415]: There should be spaces on either side of the equals sign

File: core/modules/widgets/navigator.js [hunk 2]
```diff
@@ -474,7 +476,8 @@ NavigatorWidget.prototype.handleNewTiddlerEvent = function(event) {
 		{
 			title: draftTitle,
 			"draft.of": title,
-			tags: mergedTags
+			// If template or additionalFields have "tags" even if empty a tags field will be created.
+			tags: ((mergedTags.length>0) || templateHasTags || additionalFieldsHasTags) ? mergedTags : undefined
```
Comment (Jermolene) [inline core/modules/widgets/navigator.js:480]: There should be spaces either side of the greater than sign.

**Comment by pmario** [comment]
@Jermolene added the requested tests and fixed the typos

**Comment by Jermolene** [comment]
Thanks @pmario
