### PR TITLE
Fix: Don't set dirty flag when shadow tiddler changes

### LINKED ISSUE #8902: [BUG] Updating info tiddlers using the callback sets the dirty flag
### Describe the bug

If a module of type `info` calls the `updateInfoPlugin` callback it's given after the wiki is up and running, it causes the wiki to be marked as dirty/unsaved (the save button turns red, etc.). This happens even if `updateInfoPlugin` is passed an empty array, and isn't actually changing anything.

### Expected behavior

I expected the wiki to not become dirty when info tiddlers change, since they aren't saved anyway as far as I can tell. The fact that the info pseudo-plugin is prefixed with `$:/temp/` seems to indicate that this shouldn't count as a 'real' change.

### To Reproduce

1. Download a blank TiddlyWiki.
2. Import this tiddler: https://gist.github.com/Rhys-T/5080ac9b27af73bff9fe370687087472
4. Save the wiki and reload.
5. Wait 5 seconds. The save button will turn red.

### Screenshots

_No response_

### TiddlyWiki Configuration

- Version: 5.3.6
- Saving mechanism: Timimi
- Plugins installed: none

### Desktop:

- OS: macOS
- Browser: Firefox
- Version: macOS 10.15.7, Firefox 134.0.1

### Smartphone:

Not yet tested.

### Additional context

This seems to happen because updating `$:/temp/info-plugin` causes it to be re-unpacked, which counts as a change to every tiddler inside it - including the default `$:/info/*` ones, which are included in the default `$:/config/SaverFilter`. Adding ` -[prefix[$:/info/]]` to the end of `$:/config/SaverFilter` seems to stop the info plugin from dirtying the wiki, but it was a quick test, and I don't know whether changing that has any problematic side effects or not.

### PR DESCRIPTION
**Pull request by Rhys-T**
Adds `shadow` and `normal` flags to each entry in `changedTiddlers`, indicating whether the corresponding version of the tiddler has changed. Makes the saver handler ignore any changes that aren't flagged `normal`.

Fixes #8902.

---

I've tried this instead of changing `$:/config/SaverFilter` to exclude shadows, and it seems to be working properly for me. I haven't tested it extensively, however.

### CODE REVIEW

File: core/modules/wiki.js [hunk 1]
```diff
@@ -141,12 +141,15 @@ This method should be called after the changes it describes have been made to th
 	title: Title of tiddler
 	isDeleted: defaults to false (meaning the tiddler has been created or modified),
 		true if the tiddler has been deleted
+	isShadow: defaults to false (meaning the change applies to the normal tiddler),
+		true if the tiddler being changed is a shadow tiddler
 */
-exports.enqueueTiddlerEvent = function(title,isDeleted) {
+exports.enqueueTiddlerEvent = function(title,isDeleted,isShadow) {
```
Comment (Rhys-T) [inline core/modules/wiki.js:147]: question: Is adding another parameter here okay? At what point does it need to change to an object?

File: core/modules/wiki.js [hunk 2]
```diff
@@ -141,12 +141,15 @@ This method should be called after the changes it describes have been made to th
...
 	// Record the touch in the list of changed tiddlers
 	this.changedTiddlers = this.changedTiddlers || Object.create(null);
 	this.changedTiddlers[title] = this.changedTiddlers[title] || Object.create(null);
 	this.changedTiddlers[title][isDeleted ? "deleted" : "modified"] = true;
+	this.changedTiddlers[title][isShadow ? "shadow" : "normal"] = true;
 	// Increment the change count
```
Comment (Rhys-T) [inline core/modules/wiki.js:153]: question: I'm not sure how the change count is used. Would it need to be split into shadow and normal versions?

**Comment by Jermolene** [comment]
> @Rhys-T It appears that this is your first contribution to the project, welcome.

Apologies, that message is appearing because I hadn't merged tiddlywiki-com into master since your CLA signature was merged. Should be fixed for your next commit.

File: core/modules/wiki.js (hunk 2 above)
Comment (Jermolene) [reply core/modules/wiki.js:153]: The change count is used in some situations for syncing. I do not think it needs to be split.

**Comment by Rhys-T** [comment]
No, no, it's right, I haven't actually gotten to signing it yet. Give me a minute…

**Comment by Jermolene** [comment]
Thanks @Rhys-T that's an interesting approach and I don't see any obvious flaws. Let's give it some testing.

**Comment by Rhys-T** [comment]
Submitted the CLA signature as #8904, but I'm not 100% sure I did it correctly. I missed the part about using GitHub's edit button to do it, and created the branch and PR the old-fashioned way. Do I need to redo it so it has a Git-level digital signature or anything?

File: core/modules/wiki.js (hunk 1 above)
Comment (Rhys-T) [reply core/modules/wiki.js:147]: Okay. Having lots of positional arguments of the same type can get confusing, and I wanted to make sure I wasn't taking things too far in that direction.

**Comment by pmario** [comment]
I did skim the code, and I am not sure about the initialisation -- So IMO a bit more testing is needed.

**Comment by Rhys-T** [comment]
I tried to keep everything as compatible as I could. `enqueueTiddlerEvent` will just assume the event is about a normal tiddler unless told otherwise, and as far as I understand it, the only thing that should directly mess with shadow tiddlers is the plugin-unpacking code. The `changes` object is getting new properties, but all the existing ones should be exactly the same as before. Still, I agree that it should probably be tested more thoroughly. I'm not that familiar with TW's internals, and it's entirely possible I'm missing something.

File: core/modules/startup/plugins.js [hunk 3]
```diff
@@ -75,7 +75,7 @@ exports.startup = function() {
 				$tw.wiki.unpackPluginTiddlers();
 				// Queue change events for the changed shadow tiddlers
 				$tw.utils.each(Object.keys(changedShadowTiddlers),function(title) {
-					$tw.wiki.enqueueTiddlerEvent(title,changedShadowTiddlers[title]);
+					$tw.wiki.enqueueTiddlerEvent(title,changedShadowTiddlers[title], true);
```
Comment (Rhys-T) [inline core/modules/startup/plugins.js:78]: nitpick: I forgot to leave off the space after the comma to match the rest of the code. Is it worth another force-push, or should I leave it alone?

Comment (pmario) [reply core/modules/startup/plugins.js:78]: A standard push should be fine.

**Comment by pmario** [comment]
I did some more tests with overwritten shadow tiddlers and it seems to work. 

@Jermolene -- It looks good to me.

**Comment by Jermolene** [comment]
Thanks @Rhys-T
